---
- hosts: aws_ec2
  become: true
  user: ubuntu
  gather_facts: true 
  tasks:
    - set_fact:
        APP_EXTERNAL_PORT: "{{ (lookup('template', './inventory/aws_ec2.yml')|from_yaml).APP_EXTERNAL_PORT }}"
    - name: Create and run a service
      community.docker.docker_compose: 
        project_name: todoapp
        remove_orphans: true
        definition:
          version: '2'
          services:
            mysql:
              image: mysql:5.7 
              volumes: 
                - todo-mysql-data:/var/lib/mysql
              environment:
                    MYSQL_ROOT_PASSWORD: supersecret
                    MYSQL_DATABASE: todos
            app:
              image: bugaian/getting-started
              ports:
                 - "{{APP_EXTERNAL_PORT}}" 
              depends_on:
                    - mysql 
              working_dir: /app
              
              environment:
                MYSQL_HOST: mysql
                MYSQL_USER: root
                MYSQL_PASSWORD: supersecret
                MYSQL_DB: todos
 
          volumes:
            todo-mysql-data:
      register: output

    - debug:
        var: output
    
    - name: Test app by curl http://hostname:63000 se hostname bellow from an external ip 
      debug:
        msg: " {{ 'curl http://'+ inventory_hostname +':63000' }}" 
    - name: Test web to file
      ansible.builtin.get_url:
          url: " {{ 'http://'+ inventory_hostname +':63000' }}" 
          dest: ./test.result
      register: output
      delegate_to: localhost
    - name: Get http curl result 
      debug:
        var: output 


    
  #  - ansible.builtin.assert:
   #     that:
    #      - "app.todoapp_app_1.state.running"
     #     - "db.todoapp_db_1.state.running"  
